### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by ValdikSS** [ValdikSS/ruqrypt#1]
- [ ] Change default server
- [ ] Add HTTPS support
- [ ] Add passive DPI circumvention
- [ ] Add active DPI circumvention
- [ ] Improve Linux support and iptables rules
- [ ] Add macOS support
- [ ] Increase default TTL value
- [ ] Add IP address lists (circumvent-only lists)

**Comment by basil00** [comment]
> Change default server

Updated to some new (functional) test servers:
https://github.com/basil00/reqrypt/commit/fd266355a5fc45d136dffe80578d69092375042a

> Add HTTPS support

This requires a bit of work I think, including UI changes.  Also, another problem is the lack of IPv6 support (was not really a problem in 2009, but is a problem in 2017).

> Add macOS support

Should already be supported?  I have not testing it in a long time though.

**Comment by ValdikSS** [comment]
>This requires a bit of work I think, including UI changes. Also, another problem is the lack of IPv6 support (was not really a problem in 2009, but is a problem in 2017).

Well, HTTPS is more important than IPv6. I don't think it would be that hard to add.

>Should already be supported? I have not testing it in a long time though.

Oh, it is supported now? I thought the program is Windows and Linux only.

**Comment by basil00** [comment]
> Oh, it is supported now? I thought the program is Windows and Linux only.

It is supported, see the build instructions for MacOSX in the `INSTALL` file.  The Mac build is mostly the same as FreeBSD since they are similar systems.  That said, I have not tested it in a long time, so I don't know if it still works.

**Comment by basil00** [comment]
[Latest updates.](https://github.com/basil00/reqrypt/commits/master)

> Add passive DPI circumvention
> Add active DPI circumvention

I added a "split only" mode that might be effective against some kinds of filters, similar to GoodbyeDPI.  It is also now the default mode since it does not consume server resources.

> Add HTTPS support

HTTPS should work with the latest version of ReQrypt.

Most of the major new features have now been implemented.  I may relaunch ReQrypt next week or so.

**Comment by dartraiden** [comment]
It will also be great to add MIPS support.
